# Site settings
title: Developer KimChanJung
description: A blog about Developer KimChanJung
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://kimchanjung.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 김찬정
user_description: java, spring, react
user_title: Java Back-End Developer
email: mogomezwai@gmail.com
twitter_username: KimChanJung
github_username:  https://github.com/kimchanjung
gplus_username:  KimChanJung
timezone: Asia/Seoul
future: true
markdown: kramdown
highlighter: rouge

# Google-analytics
google-analytics:
  id: "UA-165866221-1"

exclude: ['package.json', 'src' , 'node_modules']
