# Site settings
title: Developer KimChanjung
description: A blog about Developer KimChanJung
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://kimchanjung.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 김찬정
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Java Back-End Developer
email: mogomezwai@gmail.com
twitter_username: KimChanJung
github_username:  https://github.com/kimchanjung
gplus_username:  KimChanJung

# Google-analytics
google-analytics:
  id: "UA-165866221-1"

exclude: ['package.json', 'src' , 'node_modules']
